---
version: '3'
dotenv: ['.env']

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all
    silent: true

  init:
    desc: Initialize the workspace by copying .env.example to .env
    cmds:
      - cp -n .env.example .env

  build:
    desc: Build the active project specified in .env
    dir: projects/{{.CURRENT_PROJECT}}
    cmds:
      - pio run

  test:
    desc: Run host-native tests for the active project specified in .env
    dir: projects/{{.CURRENT_PROJECT}}
    cmds:
      - pio test -e native


  build:all:
    desc: Build all sandbox projects
    deps:
      - build:cyd-ntp-stratum1
      - build:cyd-ethernet-bruce
      - build:s3-tiny-stories

  test:all:
    desc: Run tests for all sandbox projects
    deps:
      - test:cyd-ntp-stratum1
      - test:cyd-ethernet-bruce
      - test:s3-tiny-stories

  build:cyd-ethernet-bruce:
    desc: Build the cyd-ethernet-bruce sandbox project
    dir: projects/cyd-ethernet-bruce
    cmds:
      - pio run

  test:cyd-ethernet-bruce:
    desc: Run host-native tests for the cyd-ethernet-bruce sandbox project
    dir: projects/cyd-ethernet-bruce
    cmds:
      - pio test -e native

  build:cyd-ntp-stratum1:
    desc: Build the cyd-ntp-stratum1 sandbox project
    dir: projects/cyd-ntp-stratum1
    cmds:
      - pio run

  test:cyd-ntp-stratum1:
    desc: Run host-native tests for the cyd-ntp-stratum1 sandbox project
    dir: projects/cyd-ntp-stratum1
    cmds:
      - pio test -e native

  build:s3-tiny-stories:
    desc: Build the s3-tiny-stories sandbox project
    dir: projects/s3-tiny-stories
    cmds:
      - pio run

  test:s3-tiny-stories:
    desc: Run host-native tests for the s3-tiny-stories sandbox project
    dir: projects/s3-tiny-stories
    cmds:
      - pio test -e native
