"""Build this project's decode table from its tokenizer.

Writes src/generated/vocab.h: token id -> raw UTF-8 bytes, so the device just
Serial.write()s the bytes of each generated token (llama2.c style). Also prints
the token ids for the demo prompt the sketch is primed with.

Specific to esp32_tinystories: one decode table, no encoder, and a fixed prompt.
"""

import argparse
from pathlib import Path

from tokenizers import Tokenizer

PROJECT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_TOK = PROJECT_DIR / "pc_tools" / "tokenizer.json"
DEFAULT_OUT = PROJECT_DIR / "src" / "generated" / "vocab.h"
PROMPT = "Once upon a time"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tokenizer", default=DEFAULT_TOK,
                    help="canonical tokenizer.json the header is built from")
    ap.add_argument("--out", default=DEFAULT_OUT, help="header to write")
    args = ap.parse_args()
    TOK, OUT = Path(args.tokenizer), Path(args.out)

    tok = Tokenizer.from_file(str(TOK))  # rejects PathLike
    V = tok.get_vocab_size()

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    # The output directory may not exist in a fresh clone.
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by pc_tools/generate_vocab.py\n"
                "// token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    ids = tok.encode(PROMPT).ids
    print(f'prompt "{PROMPT}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nPaste into the sketch:")
    print(f"static const int PROMPT_IDS[] = {{{', '.join(map(str, ids))}}};")


if __name__ == "__main__":
    main()
