[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_build.f_cpu = 240000000L   # Overclock for faster tokens!
build_flags = 
  -D BOARD_HAS_PSRAM
  -O3                            # Optimize for speed
monitor_speed = 115200
